src/FF/FastBundle/Entity/Gammes.php
<?php

namespace FF\FastBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Gammes
 *
 * @ORM\Table(name="gammes")
 * @ORM\Entity(repositoryClass="FF\FastBundle\Repository\GammesRepository")
 */
class Gammes
{
     /**
     * @ORM\OneToOne(targetEntity="FF\FastBundle\Entity\Images", cascade={"persist"})
     */
    private $images;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date = null;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description = null;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Gammes
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date = new \Datetime();
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Gammes
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Gammes
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set images
     *
     * @param \FF\FastBundle\Entity\Images $images
     *
     * @return Gammes
     */
    public function setImages(\FF\FastBundle\Entity\Images $images = null)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Get images
     *
     * @return \FF\FastBundle\Entity\Images
     */
    public function getImages()
    {
        return $this->images;
    }
}

src/FF/FastBundle/Entity/Images.php
<?php

namespace FF\FastBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Images
 *
 * @ORM\Table(name="images")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="FF\FastBundle\Repository\ImagesRepository")

 */
class Images
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;
  
    private $tempFilename;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Images
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Images
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
      public function getFile()
  {
                dump($this);

    return $this->file;
  }

 public function setFile(UploadedFile $file)
  {
    $this->file = $file;

    // On vérifie si on avait déjà un fichier pour cette entité
    if (null !== $this->url) {
      // On sauvegarde l'extension du fichier pour le supprimer plus tard
      $this->tempFilename = $this->url;

      // On réinitialise les valeurs des attributs url et alt
      $this->url = null;
      $this->alt = null;
      dump($file);
    }
  }

  /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file) {
      return;
    }

    // Le nom du fichier est son id, on doit juste stocker également son extension
    // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
    $this->url = $this->file->guessExtension();

    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
    $this->alt = $this->file->getClientOriginalName();
  }

  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
    if (null === $this->file) {
      return;
    }

    // Si on avait un ancien fichier, on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }

    // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->file->move(
      $this->getUploadRootDir(), // Le répertoire de destination
      $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
    );
  }

  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }

  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'uploads/img';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }
  
    public function getWebPath()
  {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
  }
}

src/FF/FastBundle/Form/GammesType.php
<?php

namespace FF\FastBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class GammesType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
	      ->add('name',     TextType::class)
	      ->add('description',   TextareaType::class, array('required' => false))
				->add('images',     ImagesType::class, array('required' => false)) 
	      ->add('save',      SubmitType::class);
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FF\FastBundle\Entity\Gammes'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ff_fastbundle_gammes';
    }


}

src/FF/FastBundle/Controller/GammesController.php
<?php

namespace FF\FastBundle\Controller;

use FF\FastBundle\Entity\Gammes;
use FF\FastBundle\Form\GammesType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;


class GammesController extends Controller
{
		public function indexAction($page)
		{
			if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) 
			{
				throw new AccessDeniedException('Accès limité.');
			}

			if ($page < 1) 
			{
				throw $this->createNotFoundException("La page ".$page." n'existe pas.");
			}		
			$nbPerPage = 10;

			$repository = $this->getDoctrine()
						->getManager()
						->getRepository('FFFastBundle:Gammes')
						->getGammes($page, $nbPerPage);

			$listGammes = $repository;

			$nbPages = ceil(count($listGammes) / $nbPerPage);

			 if ($page > $nbPages)
			 {
				 throw $this->createNotFoundException("La page ".$page." n'existe pas.");
			 }


				return $this->render('FFFastBundle:Gammes:index.html.twig', array(
					'listGammes' => $listGammes,
					'nbPages'         => $nbPages,
					'page'            => $page,				));

		}

    public function addAction(Request $request)
    {
			if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) 
			{
				throw new AccessDeniedException('Accès limité.');
			}

   	 	$gammes = new Gammes();					
   		$form = $this->get('form.factory')->create(GammesType::class, $gammes);

			if ($request->isMethod('POST') && $form->handleRequest($request)->isValid())
			{
				$em = $this->getDoctrine()->getManager();
				$em->persist($gammes);
				$em->flush();

				
        $request->getSession()->getFlashBag()->add('success', 'Gamme bien enregistrée.');

        return $this->redirectToRoute('ff_fast_view', array('id' => $gammes->getId()));
      }
    

        return $this->render('FFFastBundle:Gammes:add.html.twig', array(
        	'form' => $form->createView(),
        	));
    }
	

    public function viewAction($id)
    {		
			if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) 
			{
				throw new AccessDeniedException('Accès limité.');
			}
	
				$repository = $this->getDoctrine()
					->getManager()
					->getRepository('FFFastBundle:Gammes')
					;
				$gammes = $repository->find($id);
			
			if (null === $gammes) 
			{
     			 throw new NotFoundHttpException("La gamme d'id ".$id." n'existe pas.");
			}
						
      return $this->render('FFFastBundle:Gammes:view.html.twig', array(
          'gammes' => $gammes
        ));
    }


    public function editAction($id,Request $request )
    {
			if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) 
			{
				throw new AccessDeniedException('Accès limité.');
			}
			
			$em = $this->getDoctrine()->getManager();		
			$gammes = $em->getRepository('FFFastBundle:Gammes')->find($id);
			
			if (null === $gammes) 
			{
				throw new NotFoundHttpException("La gamme d'id ".$id." n'existe pas.");
			}

   		$form = $this->get('form.factory')->create(GammesType::class, $gammes);

			if ($request->isMethod('POST') && $form->handleRequest($request)->isValid())
			{
					$em = $this->getDoctrine()->getManager();
					$em->flush();
				
					$request->getSession()->getFlashBag()->add('success', 'Gamme bien modifiée.');
				
		  		return $this->redirectToRoute('ff_fast_view', array('id' => $gammes->getId()));
					
			}
			
			
			

			 return $this->render('FFFastBundle:Gammes:edit.html.twig', array(
				'gammes'=> $gammes,			
				'form' => $form->createView(),
				));

    }


		public function deleteAction(Request $request, $id)
		{
				if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) 
				{
					throw new AccessDeniedException('Accès limité.');
				}

				$em = $this->getDoctrine()->getManager();

				$gammes = $em->getRepository('FFFastBundle:Gammes')->find($id);

				if (null === $gammes) 
				{
					throw new NotFoundHttpException("La Gamme d'id ".$id." n'existe pas.");
				}
			
				$form = $this->get('form.factory')->create();

				if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) 
				{
					$em->remove($gammes);
					$em->flush();

					$request->getSession()->getFlashBag()->add('info', "La Gamme a bien été supprimée.");

					return $this->redirectToRoute('ff_fast_home');
				}

				return $this->render('FFFastBundle:Gammes:delete.html.twig', array(
					'gammes' => $gammes,
					'form'   => $form->createView(),
				));
		}
}

src/FF/FastBundle/Resources/views/Gammes/add.html.twig
{% extends "FFCoreBundle:Core:menu.html.twig" %}
 {% block title %} Ajouter une gamme - {{ parent() }}{% endblock %}
{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div id="content" class="col-md-8">
  <h2>Ajouter une Gamme de Produit </h2>

  {{ include("FFFastBundle:Gammes:form.html.twig") }}

  <p class='my-1'>
    <a href="{{ path('ff_fast_home') }}"  class="btn btn-primary ">
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Retour
    </a>
  </p>
</main>
{% endblock %}

src/FF/FastBundle/Resources/views/Gammes/delete.html.twig
{% extends "FFCoreBundle:Core:menu.html.twig" %}

{% block title %}
  Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div id="content" class="col-md-8">
  <h2>Supprimer une annonce</h2>

  <p>
    Etes-vous certain de vouloir supprimer la gamme "{{ gammes.name }}" ?
  </p>

  {# On met l'id de l'annonce dans la route de l'action du formulaire #}
  <form action="{{ path('ff_fast_delete', {'id': gammes.id}) }}" method="post">
    <a href="{{ path('ff_fast_view', {'id': gammes.id}) }}"  class="btn btn-primary ">
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Retour
    </a>
    {# Ici j'ai écrit le bouton de soumission à la main #}
    <button  type="submit" value="Supprimer" class="btn btn-danger">       
<i class="fa fa-trash" aria-hidden="true"></i>
Supprimer
</button >    {# Ceci va générer le champ CSRF #}
    {{ form_rest(form) }}
  </form>
</main>
{% endblock %}

src/FF/FastBundle/Resources/views/Gammes/edit.html.twig
{% extends "FFCoreBundle:Core:menu.html.twig" %}
 {% block title %}Modification d'une gamme - {{ parent() }} {% endblock %}
{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div id="content" class="col-md-8">
  <h2>Editer une Gamme de Produit </h2>

  {{ include("FFFastBundle:Gammes:form.html.twig") }}


  <p>
    <a href="{{ path('ff_fast_view', {'id': gammes.id}) }}" class="btn btn-primary ">
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Retour
    </a>
  </p>
</main>
{% endblock %}

src/FF/FastBundle/Resources/views/Gammes/form.html.twig
     <h3> Formulaire </h3>
		 
	<div class="well">

<form method="post">
    {{ form_start(form) }}
		<div class="form-group">
        {{ form_label(form.name, 'Nom') }}
        {{ form_errors(form.name) }}
        {{ form_widget(form.name) }}
    </div>

		 <div class="form-group">
        {{ form_label(form.description) }}
        {{ form_errors(form.description) }}
        {{ form_widget(form.description) }}
    </div>
		
		 <div class="form-group">
        {{ form_label(form.images, 'Image') }}
        {{ form_errors(form.images) }}
        {{ form_widget(form.images) }}
    </div>
		
		<div class="form-group">
				{{ form_widget(form.save, {'attr': {'class': 'btn btn-sm btn-success'}, 'label': 'Valider'}) }}
		 </div>

    {{ form_end(form) }}
</form>
</div>

src/FF/FastBundle/Resources/views/Gammes/index.html.twig
{% extends "FFCoreBundle:Core:menu.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div id="content" class="col-md-8">
{% for key, messages in app.session.flashbag.all() %}
  {% for message in messages %}
    <div class="alert alert-{{key}}">
     <strong>Succès!</strong> {{ message|trans({}, 'FFFastBundle') }}
    </div>
  {% endfor %}
{% endfor %}
  <h2>Mes Gammes</h2>

  <ul>
    {% for gammes in listGammes %}
      <li>
        <a href="{{ path('ff_fast_view', {'id': gammes.id}) }}">
          {{ gammes.name }}
        </a>
      </li>
    {% else %}
      <li>Il n'y a pas encore de gammes !</li>
    {% endfor %}
  </ul>
<nav aria-label="Page navigation example">

    <ul class="pagination">
  {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
  {% for p in range(1, nbPages) %}
    <li class="page-item" {% if p == page %} class="page-item active" {% endif %}>
      <a class="page-link" href="{{ path('ff_fast_homes', {'page': p}) }}">{{ p }}</a>
    </li>
  {% endfor %}
</ul>
</nav>
  <p>
    <a href="{{ path('ff_fast_add')}}" class="btn btn-success">
    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
      Ajouter    
    </a>
  </p>
</main>
{% endblock %}

src/FF/FastBundle/Resources/views/Gammes/view.html.twig
{% extends "FFCoreBundle:Core:menu.html.twig" %}

{% block title %}
  Lecture d'une Gamme - {{ parent() }}
{% endblock %}

{% block body %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
<div id="content" class="col-md-8">
{% for key, messages in app.session.flashbag.all() %}
  {% for message in messages %}
    <div class="alert alert-{{key}}">
     <strong>Succès!</strong> {{ message|trans({}, 'FFFastBundle') }}
    </div>
  {% endfor %}
{% endfor %}
  <h2>{{ gammes.name}}</h2>

  <div class="well">
    {{ gammes.description }}
    

  </div>
    {% if gammes.images != null %}

    <img
  {# src="{{ asset(gammes.images.webPath) }}"#}
  src="{{ gammes.images.url}}"
  alt="{{ gammes.images.alt }}"
  height="100"
/>
{% endif %}

  <p>
    <a href="{{ path('ff_fast_home') }}" class="btn btn-primary ">
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
      Retour
    </a>
    <a href="{{ path('ff_fast_edit', {'id': gammes.id}) }}" class="btn btn-warning">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      Modifier
    </a>
    <a href="{{ path('ff_fast_delete', {'id': gammes.id}) }}" class="btn btn-danger">
    <i class="fa fa-trash" aria-hidden="true"></i>
      Supprimer
    </a>
  </p>
</main>
{% endblock %}